spring.application.name=demo-login-system

# SERVER CONFIG
server.port=${PORT}
server.url=${SERVER_URL}

# DB CONFIG
spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=${JWT_SECRET}