spring.application.name=demo-login-system

# SERVER CONFIG
server.port=${PORT:3001}
server.local-domain=${SERVER_LOCAL_DOMAIN:http://localhost:3001}

# DB CONFIG
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# HIBERNATE
spring.jpa.hibernate.ddl-auto=update

# JWT
jwt.secret=${JWT_SECRET}